trigger:
  batch: true
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

schedules:
  - cron: '0 0 * * 0'
    displayName: Weekly build
    branches:
      include:
        - main
    always: true

resources:
  repositories:
    - repository: OpsGuildAutomationRepo
      type: git
      name: Engineering/OpsGuild.Automation
      ref: refs/heads/main
    - repository: templates
      type: github
      name: osisoft/OSI-Samples
      endpoint: osisoft/OSI-Samples

variables:
  - template: '/miscellaneous/build_templates/variables.yml@templates'
  - name: analysisProject
    value: Auth_PKCE_JavaScript

jobs:
  - job: Tests
    pool:
      name: 00-OSIManaged-Containers
      demands: Agent.OS -equals Windows_NT
    variables:
      - name: acr_values
        value: 'tenant:$(TenantId)'
      - name: userName
        value: $(AuthorizationUsername)
      - name: password
        value: $(AuthorizationPassword)
      - name: client_id
        value: $(AuthorizationCodeClientId)
      - name: authority
        value: $(Resource)
    steps:
      - template: '/miscellaneous/build_templates/appsettings.yml@templates'
        parameters:
          secrets: 'AuthorizationUsername, AuthorizationPassword, TenantId, AuthorizationCodeClientId, Resource'

      - script: npm ci
        displayName: 'Install dependencies'

      - script: npm i chromedriver --detect_chromedriver_version
        displayName: 'Install chromedriver'

      - script: start /B npm start
        displayName: 'Run app'

      - script: npm test
        displayName: 'Run tests'

      - task: PublishTestResults@2
        inputs:
          testResultsFormat: JUnit
          testResultsFiles: '*.xml'
          failTaskOnFailedTests: true
          searchFolder: '$(Build.SourcesDirectory)/TestResults'
          testRunTitle: '$(Agent.JobName) on $(Agent.OS)'
        displayName: 'Publish test results'
        condition: always()

  - template: '/miscellaneous/build_templates/code-analysis.yml@templates'
